### ISSUE TITLE
Yoshi Touch & Go - fails to boot

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#11]
This game is crashing on boot. Tested on Windows and Ubuntu using master.
Log:
```
Save size: 512

POWCNT1: $0000
A9 offset: $00004000 entry: $02000800 RAM: $02000000 size: $00087568
A7 offset: $0008BA00 entry: $02380000 RAM: $02380000 size: $00025F70

ITCM size: $00000000
DTCM base: $027C0000
DTCM size: $00000000
POWCNT1: $8000
POWCNT1: $820E
POWCNT1: $820F
POWCNT1: $820F
POWCNT1: $020F
(9) Unrecognized byte read from $0400004CQObject::~QObject: Timers cannot be stopped from another thread
Press <RETURN> to close this window...
```

**Comment by PSI-Rockin** [comment]
Oops, forgot to comment out an exit(1) call.

**Comment by PSI-Rockin** [comment]
Alright, check what happens on the master branch now.

**Comment by Simonx22** [comment]
This game still crashes.
```
READ_MEM: 0
Deselected AUXSPI
AUXSPIDATA: $0005
AUXSPI read status reg
AUXSPIDATA: $0000
Deselected AUXSPI
AUXSPIDATA: $0006
AUXSPI write enabled
Deselected AUXSPI
AUXSPIDATA: $000B
Unrecognized AUXSPI cmd 11QObject::~QObject: Timers cannot be stopped from another thread
Press <RETURN> to close this window...
```

**Comment by PSI-Rockin** [comment]
Looks like this game uses a 512 byte EEPROM for saving, and I don't support that protocol yet. I'll look at this later.

**Comment by PSI-Rockin** [comment]
I've added a protocol for 512 byte EEPROM, which should fix the boot problem. I don't know how reliable it is however.

By the way, #12 should be fixed as well.

**Comment by Simonx22** [comment]
Awesome, it fixed the issue. #12 isn't fixed sadly. I will paste the log there.
