### ISSUE TITLE
Can't use mouse in the GUI

### ISSUE THREAD

**Issue by literalmente-game** [PSI-Rockin/CorgiDS#2]
I've compiled the version 0.1, and while trying to use it I was unable to click on any option in the menus.
The only way I was able to use the GUI was by pressing "Alt"+"F" or "Alt+E" (the shortcuts via keyboard)

**Comment by robozman** [comment]
I experienced the same issue after compiling myself on Arch Linux

**Comment by trbocode** [comment]
Same here.

**Comment by PSI-Rockin** [comment]
I assume all of you are using Arch Linux.

What happens when you try to run a ROM?

**Comment by trbocode** [comment]
Unrecognizedf halfwork reads from everything, sequentally. 2fps. Tried MK DS, PSMD1, Stratego, and Chinese NSMB (Dunno why I had it).
btw i use arch

**Comment by PSI-Rockin** [comment]
Very odd. Could you send part of the console log from the beginning of MKDS? (Pastebin works) That game is known to work.

**Comment by literalmente-game** [comment]
To be clear, I'm using Windows 7. Not a single game was able to run so far

**Comment by PSI-Rockin** [comment]
Which version of Qt are you guys using? I'm using Qt 5.9.1. Maybe the version has something to do with it? Try updating to the newest version if you don't have it.

If that's not the problem, then I think it's an issue with the multithreading going on. CorgiDS places emulation on a separate thread, and it's not entirely robust.

**Comment by literalmente-game** [comment]
I'm updating to 5.9.1 now, was using 5.7

**Comment by PSI-Rockin** [comment]
To those who were having "unrecognized halfword" errors before:
The ARM9/ARM7 labels on the config screen were flipped, embarrassingly enough. I pushed some changes to the repository to fix that. Either go ahead and download the new changes or just flip the locations of the BIOS files in the config.

**Comment by literalmente-game** [comment]
Okay, I've updated my QT to 5.9.1 and compiled using the up to date code (https://github.com/PSI-Rockin/CorgiDS/tree/f30841b53fb604018a9140201cf25f6eb15cc892), the GUI still have the same issue. There is nothing to be embarassed about, your project is very impressive so far ;)

**Comment by Simonx22** [comment]
I compiled CorgiDS for Windows and can't select anything in the window either. I'm using the latest master.

**Comment by PSI-Rockin** [comment]
Once you've flipped your BIOS files around, do the ROMs work? If so, could you check if touchscreen input works during a game? I'm wondering if the way CorgiDS handles the touchscreen is causing problems.

**Comment by literalmente-game** [comment]
After changing the BIOS files, I was able to run my games properly, the touchscreen is working as intended too

**Comment by PSI-Rockin** [comment]
I'm going to create a new branch for fixing these Windows GUI issues, starting with disabling touchscreen input and framebuffer output.

**Comment by PSI-Rockin** [comment]
I have created the "fix_windows" branch, where the mouse events and threading (and indirectly, framebuffer output) have been disabled. Windows users, please check if this allows the menubar to be used.

**Comment by literalmente-game** [comment]
Compiled and confirmed, the issue is fixed in the new branch

**Comment by PSI-Rockin** [comment]
Alright, I'll be pushing something new shortly that will re-enable emulation and touchscreen input.

**Comment by PSI-Rockin** [comment]
Done, please confirm that everything works.

**Comment by literalmente-game** [comment]
I've tested with Mario Kart, loading fine and the touchscreen is working as well

**Comment by robozman** [comment]
Works fine now for me as well on Arch Linux

**Comment by robozman** [comment]
Works fine on Arch Linux with the "fix-windows" branch
